disabled_rules:
  - todo
  - type_name
  - line_length
  - xctfail_message

force_cast:
  severity: warning

force_try:
  severity: warning

line_length:
  warning: 120

nesting:
  type_level: 4
  statement_level: 5

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 3
  excluded:
    - id
    - vc
    - nc
