name: Lint

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/config/swiftlint.yml'
      - '**/*.swift'

jobs:
  lint:
    runs-on: macos-latest
    timeout-minutes: 1
    name: Linter
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: |
          brew install swiftlint
      - name: Run linter
        run: |
          swiftlint lint --strict --config ".github/config/swiftlint.yml" --reporter github-actions-logging
