name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/config/swiftlint.yml'
      - '**/*.swift'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Linter
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run linter
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict --config .github/config/swiftlint.yml
