name: Sample

on: workflow_dispatch

jobs:
  publish:
    name: Sample
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run
        run: |
          ls -n /Applications/ | grep Xcode*
